/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tabelas;

import Classes.Prontuario;
import Classes.SistemaClinicaMedica;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Painel com a interface de tabela de informações dos prontuarios
 */
public class TabelaProntuarios extends javax.swing.JPanel {
    
    /**
     * Creates new form PainelTabelaProntuarios
     */
    public TabelaProntuarios() {
        initComponents();
    }

    /**
     * Creates new form PainelTabelaProntuarios
     * @param sistema Sistema da clínica
     */
    public TabelaProntuarios(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new java.awt.Dimension(420, 360));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Médico", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Atualiza a lista de prontuarios com base na pesquisa
     */
    private void atualizarLista() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        Calendar calendar = Calendar.getInstance();
        
        for (Prontuario prontuario: prontuarios) {
            calendar.setTime(prontuario.getDataCriacao());
            int ano = calendar.get(Calendar.YEAR);
            int mes = calendar.get(Calendar.MONTH) + 1;
            int dia = calendar.get(Calendar.DAY_OF_MONTH);
            int hora = calendar.get(Calendar.HOUR_OF_DAY);
            int minuto = calendar.get(Calendar.MINUTE);
            String data = ano + "/" + mes + "/" + dia + " " + hora + ":" + minuto;
            
            model.addRow(
                new Object[]{
                    prontuario.getPaciente().getNome(),
                    prontuario.getMedico().getNome(),
                    data
                }
            );
        }
    }
    
    /**
     * Retorna a prontuario selecionada
     * @return Prontuario
     */
    public Prontuario obterSelecionado() {
        Prontuario prontuario;
        int row = table.getSelectedRow();
        if (row >= 0) {
            prontuario = prontuarios.get(row);
        } else {
            prontuario = null;
        }
        return prontuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private SistemaClinicaMedica sistema;
    private List<Prontuario> prontuarios;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public List<Prontuario> getProntuarios() {
        return prontuarios;
    }

    public void setProntuarios(List<Prontuario> prontuarios) {
        this.prontuarios = prontuarios;
        atualizarLista();
    }
    
    
}
