/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Consulta;
import Classes.Medico;
import Classes.SistemaClinicaMedica;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.List;

/**
 * Painel com interface para registrar paciente
 */
public class PainelRegistroConsulta extends javax.swing.JPanel {
    
    /**
     * Construtor do painel
     */
    public PainelRegistroConsulta() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelRegistroConsulta(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoTextoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTextoDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        campoTextoTipo = new javax.swing.JTextField();
        tabelaMedicos = new Tabelas.TabelaMedicos();
        jLabel13 = new javax.swing.JLabel();
        campoTextoNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoTextoCPF = new javax.swing.JTextField();
        botaoRegistrar = new javax.swing.JButton();
        campoTextoHora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoTextoMinuto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoTextoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAnoActionPerformed(evt);
            }
        });
        add(campoTextoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 70, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registrar nova consulta");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 270, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ano");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 30, 20));

        campoTextoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMesActionPerformed(evt);
            }
        });
        add(campoTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 70, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mês");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 30, 20));

        campoTextoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoDiaActionPerformed(evt);
            }
        });
        add(campoTextoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 70, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 30, 20));

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        botaoBuscar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoBuscar.setText("Buscar médico");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        add(botaoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 120, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Tipo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 40, 20));

        campoTextoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTipoActionPerformed(evt);
            }
        });
        add(campoTextoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 120, -1));
        add(tabelaMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nome");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 40, 20));

        campoTextoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNomeActionPerformed(evt);
            }
        });
        add(campoTextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("CPF");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 40, 20));

        campoTextoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFActionPerformed(evt);
            }
        });
        add(campoTextoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 120, -1));

        botaoRegistrar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoRegistrar.setText("Registrar");
        botaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarActionPerformed(evt);
            }
        });
        add(botaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 120, -1));

        campoTextoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoHoraActionPerformed(evt);
            }
        });
        add(campoTextoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 70, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Hora");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 30, 20));

        campoTextoMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMinutoActionPerformed(evt);
            }
        });
        add(campoTextoMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 70, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Minuto");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 40, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAnoActionPerformed

    private void campoTextoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMesActionPerformed

    private void campoTextoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoDiaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) getParent()).mostrarPainel("Consulta");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        List<Medico> medicos = sistema.pesquisarMedicos(campoTextoNome.getText(), campoTextoCPF.getText());
        tabelaMedicos.setMedicos(medicos);
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void campoTextoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTipoActionPerformed

    private void campoTextoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNomeActionPerformed

    private void campoTextoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFActionPerformed

    private void botaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarActionPerformed
        if (Verificar()) {
            registrarConsulta();
            ((PainelClinicaMedica) getParent()).mostrarPainel("Consulta");
        }
    }//GEN-LAST:event_botaoRegistrarActionPerformed

    private void campoTextoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoHoraActionPerformed

    private void campoTextoMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMinutoActionPerformed

    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean Verificar() {
        boolean correto = true;
        String conteudoAviso = null;
        
        Medico medico = tabelaMedicos.obterSelecionado();
        if (medico == null) {
            conteudoAviso = "Selecione um médico antes";
            correto = false;
        }
       
       if (campoTextoTipo.getText().length() == 0) {
            conteudoAviso = "Tipo não foi preenchido";
            correto = false;
       }
       
       try {
            Integer.valueOf(campoTextoAno.getText());
            Integer.valueOf(campoTextoMes.getText());
            Integer.valueOf(campoTextoDia.getText());
            Integer.valueOf(campoTextoHora.getText());
            Integer.valueOf(campoTextoMinuto.getText());
            
       } catch (NumberFormatException erro) {
            conteudoAviso = "A data da consulta está incorreta";
            correto = false;
       }
       
       if (conteudoAviso != null) {
            JOptionPane.showMessageDialog(this, conteudoAviso, "Aviso", JOptionPane.WARNING_MESSAGE);
       }
       
       return correto;
    }
    
    /**
     * Cadastra a consulta no banco de dados
     */
    private void registrarConsulta() {
        Consulta consulta = new Consulta();
        
        consulta.setPaciente(sistema.obterPaciente(idPaciente));
        consulta.setMedico(tabelaMedicos.obterSelecionado());
        consulta.setTipo(campoTextoTipo.getText());
        Calendar calendar = Calendar.getInstance();
        calendar.set(
            Integer.parseInt(campoTextoAno.getText()), 
            Integer.parseInt(campoTextoMes.getText()) - 1, 
            Integer.parseInt(campoTextoDia.getText())
        );
        calendar.set(Calendar.HOUR_OF_DAY, Integer.parseInt(campoTextoHora.getText()));
        calendar.set(Calendar.MINUTE, Integer.parseInt(campoTextoMinuto.getText()));
        
        consulta.setDataMarcada(calendar.getTime());
        
        sistema.registrarConsulta(consulta);
        JOptionPane.showMessageDialog(this, 
            "Consulta cadastrada no banco de dados com sucesso", 
            "Aviso", 
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoRegistrar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoAno;
    private javax.swing.JTextField campoTextoCPF;
    private javax.swing.JTextField campoTextoDia;
    private javax.swing.JTextField campoTextoHora;
    private javax.swing.JTextField campoTextoMes;
    private javax.swing.JTextField campoTextoMinuto;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JTextField campoTextoTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Tabelas.TabelaMedicos tabelaMedicos;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idPaciente;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdPaciente() {
        return idPaciente;
    }

    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    
}
