/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Consulta;
import Classes.Paciente;
import Classes.Secretaria;
import Classes.SistemaClinicaMedica;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Painel com interface para gerenciamento de consultas
 */
public class PainelConsulta extends javax.swing.JPanel {

    /**
     * Creates new form PanelTeste2
     */
    public PainelConsulta() {
        initComponents();
    }
    
    /**
     * Creates new form PanelTeste2
     * @param sistema Sistema da clínica
     */
    public PainelConsulta(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        botaoRemoverConsulta = new javax.swing.JButton();
        campoPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botaoEditarPaciente = new javax.swing.JButton();
        botaoRegistrarConsulta = new javax.swing.JButton();
        tabelaConsultas = new Tabelas.TabelaConsultas();
        campoMedico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Sair");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        add(botaoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 140, -1));

        botaoRemoverConsulta.setText("Remover consulta");
        botaoRemoverConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverConsultaActionPerformed(evt);
            }
        });
        add(botaoRemoverConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 150, -1));

        campoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPacienteActionPerformed(evt);
            }
        });
        add(campoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Paciente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, 20));

        botaoEditarPaciente.setText("Editar consulta");
        botaoEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarPacienteActionPerformed(evt);
            }
        });
        add(botaoEditarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 150, -1));

        botaoRegistrarConsulta.setText("Registrar consulta");
        botaoRegistrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarConsultaActionPerformed(evt);
            }
        });
        add(botaoRegistrarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 150, -1));
        add(tabelaConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        campoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMedicoActionPerformed(evt);
            }
        });
        add(campoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Médico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 20));

        campoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoActionPerformed(evt);
            }
        });
        add(campoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 130, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tipo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 30, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Consultas");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Secretaria");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        realizarBusca();
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoRemoverConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverConsultaActionPerformed
        Consulta consulta = tabelaConsultas.obterSelecionado();
        if (consulta != null) {
            sistema.removerConsulta(consulta.getId());
            JOptionPane.showMessageDialog(
                this, 
                "Consulta removida do banco de dados com sucesso", 
                "Consulta removida", 
                JOptionPane.INFORMATION_MESSAGE
            );
            realizarBusca();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_botaoRemoverConsultaActionPerformed

    private void campoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPacienteActionPerformed

    private void botaoEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarPacienteActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        Consulta consulta = tabelaConsultas.obterSelecionado();
        if (consulta != null) {
            painel.getPainelEdicaoConsulta().setIdConsulta(consulta.getId());
            painel.mostrarPainel("EditarConsulta");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoEditarPacienteActionPerformed

    private void botaoRegistrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarConsultaActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        painel.getPainelRegistroConsulta().setIdPaciente(idPaciente);
        painel.mostrarPainel("RegistrarConsulta");
    }//GEN-LAST:event_botaoRegistrarConsultaActionPerformed

    private void campoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMedicoActionPerformed

    private void campoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoActionPerformed
    
    private void realizarBusca() {
        List<Consulta> consultas = sistema.pesquisarConsultas(
            campoPaciente.getText(),
            campoMedico.getText(),
            campoTipo.getText()
        );
        tabelaConsultas.setConsultas(consultas);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditarPaciente;
    private javax.swing.JButton botaoRegistrarConsulta;
    private javax.swing.JButton botaoRemoverConsulta;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoMedico;
    private javax.swing.JTextField campoPaciente;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Tabelas.TabelaConsultas tabelaConsultas;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idPaciente;

    public Integer getIdPaciente() {
        return idPaciente;
    }

    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }
    
}
