/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.SistemaClinicaMedica;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 * Painel do sistema da clínica médica
 */
public class PainelClinicaMedica extends javax.swing.JPanel {

    /**
     * Creates new form PainelClinicaMedica
     */
    public PainelClinicaMedica() {
        initComponents();
        SwingUtilities.invokeLater(() -> {
            mostrarPainel("Inicio");
        });
    }
    
    /**
     * Creates new form PainelClinicaMedica
     * @param sistema Sistema da clínica
     */
    public PainelClinicaMedica(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
        SwingUtilities.invokeLater(() -> {
            mostrarPainel("Inicio");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSecretaria1 = new Paineis.PainelSecretaria();
        painelInicial = new Paineis.PainelInicial();
        painelRegistrarMedico = new Paineis.PainelRegistroMedico(sistema);
        painelRegistrarSecretaria = new Paineis.PainelRegistroSecretaria(sistema);
        painelAcesso = new Paineis.PainelAcesso(sistema);
        painelMedico = new PainelMedico(sistema);
        painelGerenciadorDadosAdicionais = new Paineis.PainelDadosAdicionais(sistema);
        painelSecretaria = new PainelSecretaria(sistema);
        painelRegistroPaciente = new PainelRegistroPaciente(sistema);
        painelEdicaoPaciente = new PainelEdicaoPaciente(sistema);
        painelEdicaoConsulta = new PainelEdicaoConsulta(sistema);
        painelConsulta = new PainelConsulta(sistema);
        painelRegistroConsulta = new PainelRegistroConsulta(sistema);
        painelRelatorioConsultas = new PainelRelatorioConsultas(sistema);
        painelRegistroProntuario = new PainelRegistroProntuario(sistema);
        painelEdicaoProntuario = new PainelEdicaoProntuario(sistema);
        painelRelatorioProntuarios = new PainelRelatorioProntuarios(sistema);
        painelProntuario = new PainelProntuario(sistema);

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());
        add(painelInicial, "Inicio");
        add(painelRegistrarMedico, "RegistrarMedico");
        add(painelRegistrarSecretaria, "RegistrarSecretaria");
        add(painelAcesso, "Acessar");
        add(painelMedico, "Medico");
        add(painelGerenciadorDadosAdicionais, "GerenciarDadosAdicionais");
        add(painelSecretaria, "Secretaria");
        add(painelRegistroPaciente, "RegistrarPaciente");
        add(painelEdicaoPaciente, "EditarPaciente");
        add(painelEdicaoConsulta, "EditarConsulta");
        add(painelConsulta, "Consulta");
        add(painelRegistroConsulta, "RegistrarConsulta");
        add(painelRelatorioConsultas, "RelatorioConsultas");
        add(painelRegistroProntuario, "RegistrarProntuario");
        add(painelEdicaoProntuario, "EditarProntuario");
        add(painelRelatorioProntuarios, "RelatorioProntuarios");
        add(painelProntuario, "Prontuario");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paineis.PainelAcesso painelAcesso;
    private Paineis.PainelConsulta painelConsulta;
    private Paineis.PainelEdicaoConsulta painelEdicaoConsulta;
    private Paineis.PainelEdicaoPaciente painelEdicaoPaciente;
    private Paineis.PainelEdicaoProntuario painelEdicaoProntuario;
    private Paineis.PainelDadosAdicionais painelGerenciadorDadosAdicionais;
    private Paineis.PainelInicial painelInicial;
    private Paineis.PainelMedico painelMedico;
    private Paineis.PainelProntuario painelProntuario;
    private Paineis.PainelRegistroMedico painelRegistrarMedico;
    private Paineis.PainelRegistroSecretaria painelRegistrarSecretaria;
    private Paineis.PainelRegistroConsulta painelRegistroConsulta;
    private Paineis.PainelRegistroPaciente painelRegistroPaciente;
    private Paineis.PainelRegistroProntuario painelRegistroProntuario;
    private Paineis.PainelRelatorioConsultas painelRelatorioConsultas;
    private Paineis.PainelRelatorioProntuarios painelRelatorioProntuarios;
    private Paineis.PainelSecretaria painelSecretaria;
    private Paineis.PainelSecretaria painelSecretaria1;
    // End of variables declaration//GEN-END:variables
    
    /**
    * Mostra um painel na interface
    * @param nomePainel identificador do painel a ser trocado
    */
    public void mostrarPainel(String nomePainel) {
        ((CardLayout) getLayout()).show(this, nomePainel);
    }
    
    private SistemaClinicaMedica sistema;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public PainelAcesso getPainelEntrar() {
        return painelAcesso;
    }

    public PainelInicial getPainelInicial() {
        return painelInicial;
    }

    public PainelMedico getPainelMedico() {
        return painelMedico;
    }

    public PainelRegistroMedico getPainelRegistrarMedico() {
        return painelRegistrarMedico;
    }

    public PainelRegistroSecretaria getPainelRegistrarSecretaria() {
        return painelRegistrarSecretaria;
    }

    public PainelDadosAdicionais getPainelGerenciadorDadosAdicionais() {
        return painelGerenciadorDadosAdicionais;
    }

    public PainelSecretaria getPainelSecretaria() {
        return painelSecretaria;
    }

    public PainelEdicaoPaciente getPainelEdicaoPaciente() {
        return painelEdicaoPaciente;
    }

    public PainelAcesso getPainelAcesso() {
        return painelAcesso;
    }

    public PainelConsulta getPainelConsulta() {
        return painelConsulta;
    }

    public PainelEdicaoConsulta getPainelEdicaoConsulta() {
        return painelEdicaoConsulta;
    }

    public PainelRegistroConsulta getPainelRegistroConsulta() {
        return painelRegistroConsulta;
    }

    public PainelRegistroPaciente getPainelRegistroPaciente() {
        return painelRegistroPaciente;
    }

    public PainelEdicaoProntuario getPainelEdicaoProntuario() {
        return painelEdicaoProntuario;
    }

    public PainelRegistroProntuario getPainelRegistroProntuario() {
        return painelRegistroProntuario;
    }

    public PainelRelatorioConsultas getPainelRelatorioConsultas() {
        return painelRelatorioConsultas;
    }

    public PainelProntuario getPainelProntuario() {
        return painelProntuario;
    }

    public PainelRelatorioProntuarios getPainelRelatorioProntuarios() {
        return painelRelatorioProntuarios;
    }
    
    
}
