/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Paciente;
import Classes.SistemaClinicaMedica;

/**
 * Painel com interface de gerenciamento de dados adicionais
 */
public class PainelDadosAdicionais extends javax.swing.JPanel {
    
    /**
     * Construtor do painel
     */
    public PainelDadosAdicionais() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelDadosAdicionais(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoElementosPrejudiciais = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTextoComorbidades = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTextoCirurgias = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTextoAlergias = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        areaTextoElementosPrejudiciais.setColumns(20);
        areaTextoElementosPrejudiciais.setRows(5);
        jScrollPane1.setViewportView(areaTextoElementosPrejudiciais);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 480, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Elementos prejudiciais");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        areaTextoComorbidades.setColumns(20);
        areaTextoComorbidades.setRows(5);
        jScrollPane2.setViewportView(areaTextoComorbidades);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 480, 100));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Comorbidades");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        areaTextoCirurgias.setColumns(20);
        areaTextoCirurgias.setRows(5);
        jScrollPane3.setViewportView(areaTextoCirurgias);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 480, 100));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cirurgias");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 120, -1));

        areaTextoAlergias.setColumns(20);
        areaTextoAlergias.setRows(5);
        jScrollPane4.setViewportView(areaTextoAlergias);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 480, 100));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Alergias");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Editar dados adicionais");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        sistema.atualizarDadosAdicionaisPaciente(
            idPaciente,
            areaTextoElementosPrejudiciais.getText(), 
            areaTextoComorbidades.getText(), 
            areaTextoCirurgias.getText(), 
            areaTextoAlergias.getText()
        );
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Medico");
    }//GEN-LAST:event_botaoVoltarActionPerformed
    
    /**
     * Atualiza as areas de texto da interface
     */
    private void atualizarAreas() {
        Paciente paciente = sistema.obterPaciente(idPaciente);
        areaTextoElementosPrejudiciais.setText(paciente.getComportamentosPrejudiciais());
        areaTextoComorbidades.setText(paciente.getComorbidades());
        areaTextoCirurgias.setText(paciente.getCirurgias());
        areaTextoAlergias.setText(paciente.getAlergias());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoAlergias;
    private javax.swing.JTextArea areaTextoCirurgias;
    private javax.swing.JTextArea areaTextoComorbidades;
    private javax.swing.JTextArea areaTextoElementosPrejudiciais;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idPaciente;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdPaciente() {
        return idPaciente;
    }

    public void setIdPaciente(Integer IdPaciente) {
        this.idPaciente = IdPaciente;
        atualizarAreas();
    }
    
    
}
