/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Paciente;
import Classes.SistemaClinicaMedica;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;

/**
 * Painel com interface de edição dos dados adicionais do paciente
 */
public class PainelEdicaoPaciente extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelTeste2
     */
    public PainelEdicaoPaciente() {
        initComponents();
    }
    
    /**
     * Creates new form PanelTeste2
     * @param sistema Sistema da clínica
     */
    public PainelEdicaoPaciente(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoTextoCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoTextoTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoTextoAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoTextoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTextoDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoConcluir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        campoTextoEmail = new javax.swing.JTextField();
        campoTextoConvenio = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoTextoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNomeActionPerformed(evt);
            }
        });
        add(campoTextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 250, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 20));

        campoTextoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFActionPerformed(evt);
            }
        });
        add(campoTextoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 250, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CPF");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, 20));

        campoTextoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTelefoneActionPerformed(evt);
            }
        });
        add(campoTextoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 250, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefone");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 70, 20));

        campoTextoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAnoActionPerformed(evt);
            }
        });
        add(campoTextoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 50, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Editar paciente");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 270, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ano");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 30, 20));

        campoTextoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMesActionPerformed(evt);
            }
        });
        add(campoTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 50, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mês");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 30, 20));

        campoTextoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoDiaActionPerformed(evt);
            }
        });
        add(campoTextoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 50, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 30, 20));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Data de nascimento");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 130, 20));

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        botaoConcluir.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoConcluir.setText("Concluir");
        botaoConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConcluirActionPerformed(evt);
            }
        });
        add(botaoConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Convênio");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 70, 20));

        campoTextoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEmailActionPerformed(evt);
            }
        });
        add(campoTextoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 250, -1));

        campoTextoConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoConvenioActionPerformed(evt);
            }
        });
        add(campoTextoConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNomeActionPerformed

    private void campoTextoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFActionPerformed

    private void campoTextoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTelefoneActionPerformed

    private void campoTextoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAnoActionPerformed

    private void campoTextoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMesActionPerformed

    private void campoTextoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoDiaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) getParent()).mostrarPainel("Secretaria");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConcluirActionPerformed
        if (Verificar()) {
            boolean atualizado = atualizarPaciente();
            if (atualizado) {
                PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
                painel.mostrarPainel("Secretaria");
            }
        }
    }//GEN-LAST:event_botaoConcluirActionPerformed

    private void campoTextoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEmailActionPerformed

    private void campoTextoConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoConvenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoConvenioActionPerformed

    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean Verificar() {
        boolean correto = true;
        String conteudoAviso = null;
       
       if (campoTextoNome.getText().length() == 0) {
            conteudoAviso = "Nome não foi preenchido";
            correto = false;
       }
       
       if (campoTextoCPF.getText().length() == 0) {
            conteudoAviso = "CPF não foi preenchido";
            correto = false;
       }
       
       if (campoTextoConvenio.getText().length() == 0) {
            conteudoAviso = "Area médica não foi preenchida";
            correto = false;
       }
       
       try {
            Integer.valueOf(campoTextoAno.getText());
            Integer.valueOf(campoTextoMes.getText());
            Integer.valueOf(campoTextoDia.getText());
            
       } catch (NumberFormatException erro) {
            conteudoAviso = "A data de nascimento está incorreta";
            correto = false;
       }
       
       if (conteudoAviso != null) {
            JOptionPane.showMessageDialog(this, conteudoAviso, "Aviso", JOptionPane.WARNING_MESSAGE);
       }
       
       return correto;
    }
    
    /**
     * Cadastra o médico no banco de dados
     * @return retorna o dados registrados
     */
    private boolean atualizarPaciente() {
        boolean atualizado;
        Calendar calendar = Calendar.getInstance();
        calendar.set(
            Integer.parseInt(campoTextoAno.getText()), 
            Integer.parseInt(campoTextoMes.getText()) - 1, 
            Integer.parseInt(campoTextoDia.getText())
        );
        Date data = calendar.getTime();
        String erro = sistema.atualizarDadosPaciente(
            idPaciente, 
            campoTextoNome.getText(),
            campoTextoCPF.getText(),
            campoTextoTelefone.getText(),
            campoTextoEmail.getText(),
            data,
            campoTextoConvenio.getText()
        );
        if (erro == null) {
            atualizado = true;
        } else {
            atualizado = false;
            JOptionPane.showMessageDialog(this, erro, "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        return atualizado;
    }
    
    /**
     * Atualiza os campos de texto da interface
     */
    public void atualizarCampos() {
        Paciente paciente = sistema.obterPaciente(idPaciente);
        campoTextoNome.setText(paciente.getNome());
        campoTextoCPF.setText(paciente.getCpf());
        campoTextoTelefone.setText(paciente.getTelefone());
        campoTextoEmail.setText(paciente.getEmail());
        campoTextoConvenio.setText(paciente.getConvenio());
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(paciente.getDataNascimento());
        campoTextoAno.setText(Integer.toString(calendar.get(Calendar.YEAR)));
        campoTextoMes.setText(Integer.toString(calendar.get(Calendar.MONTH) + 1));
        campoTextoDia.setText(Integer.toString(calendar.get(Calendar.DAY_OF_MONTH)));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoAno;
    private javax.swing.JTextField campoTextoCPF;
    private javax.swing.JTextField campoTextoConvenio;
    private javax.swing.JTextField campoTextoDia;
    private javax.swing.JTextField campoTextoEmail;
    private javax.swing.JTextField campoTextoMes;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JTextField campoTextoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idPaciente;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdPaciente() {
        return idPaciente;
    }

    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
        atualizarCampos();
    }
    
    
}
