/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Consulta;
import Classes.Paciente;
import Classes.Secretaria;
import Classes.SistemaClinicaMedica;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Painel com interface para gerar relatórios de consulta
 */
public class PainelRelatorioConsultas extends javax.swing.JPanel {

    /**
     * Construtor do painel
     */
    public PainelRelatorioConsultas() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelRelatorioConsultas(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        botaoEnviarMensagem = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        campoTextoAno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoTextoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTextoDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botaoChecagemFiltro = new javax.swing.JCheckBox();
        botaoGerarRelatorio1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Sair");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        botaoEnviarMensagem.setText("Gerar relatório de consultas");
        botaoEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarMensagemActionPerformed(evt);
            }
        });
        add(botaoEnviarMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 190, -1));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new java.awt.Dimension(420, 360));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Medico", "Data", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 550, 440));

        campoTextoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAnoActionPerformed(evt);
            }
        });
        add(campoTextoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 50, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ano");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, 20));

        campoTextoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMesActionPerformed(evt);
            }
        });
        add(campoTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 50, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mês");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 30, 20));

        campoTextoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoDiaActionPerformed(evt);
            }
        });
        add(campoTextoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 50, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 30, 20));

        botaoChecagemFiltro.setText("Tem contato");
        botaoChecagemFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoChecagemFiltroActionPerformed(evt);
            }
        });
        add(botaoChecagemFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        botaoGerarRelatorio1.setText("Enviar mensagens avisando");
        botaoGerarRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorio1ActionPerformed(evt);
            }
        });
        add(botaoGerarRelatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Secretaria");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarMensagemActionPerformed
        if (verificar()) {
            gerarRelatorio();    
        }
    }//GEN-LAST:event_botaoEnviarMensagemActionPerformed

    private void campoTextoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAnoActionPerformed

    private void campoTextoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMesActionPerformed

    private void campoTextoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoDiaActionPerformed

    private void botaoChecagemFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoChecagemFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoChecagemFiltroActionPerformed

    private void botaoGerarRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorio1ActionPerformed
        if (verificar()) {
            int avisadosPorTelefone = 0;
            int avisadosPorEmail = 0;
            int semContato = 0;

            List<Consulta> consultas = sistema.pesquisarConsultas(
                Integer.parseInt(campoTextoAno.getText()),
                Integer.parseInt(campoTextoMes.getText()) - 1,
                Integer.parseInt(campoTextoDia.getText()),w
                botaoChecagemFiltro.isSelected()
            );

            for (Consulta consulta: consultas) {
                Paciente paciente = consulta.getPaciente();
                if (paciente.getTelefone().length() > 0) {
                    avisadosPorTelefone ++;
                } else {
                    if (paciente.getEmail().length() > 0) {
                        avisadosPorEmail ++;
                    } else {
                        semContato ++;
                    }
                }
            }

            String mensagem =
                "Pessoas avisadas por sms: " + avisadosPorTelefone + "\n" +
                "Pessoas avisadas por email: " + avisadosPorEmail + "\n" +
                "Pessoas sem contato: " + semContato;

            JOptionPane.showMessageDialog(
                this,
                mensagem,
                "Resultado do envio",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_botaoGerarRelatorio1ActionPerformed
    
    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean verificar() {
        boolean correto;
       
       try {
            Integer.valueOf(campoTextoAno.getText());
            Integer.valueOf(campoTextoMes.getText());
            Integer.valueOf(campoTextoDia.getText());
            correto = true;
       } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(this, "A data está incorreta", "Aviso", JOptionPane.WARNING_MESSAGE);
            correto = false;
       }
       
       return correto;
    }
    
    private void gerarRelatorio() {
        List<Consulta> consultas = sistema.pesquisarConsultas(
            Integer.parseInt(campoTextoAno.getText()),
            Integer.parseInt(campoTextoMes.getText()) - 1,
            Integer.parseInt(campoTextoDia.getText()),
            botaoChecagemFiltro.isSelected()
        );
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        Calendar calendar = Calendar.getInstance();
        for (Consulta consulta: consultas) {
            calendar.setTime(consulta.getDataMarcada());
            int ano = calendar.get(Calendar.YEAR);
            int mes = calendar.get(Calendar.MONTH) + 1;
            int dia = calendar.get(Calendar.DAY_OF_MONTH);
            int hora = calendar.get(Calendar.HOUR_OF_DAY);
            int minuto = calendar.get(Calendar.MINUTE);
            String data = ano + "/" + mes + "/" + dia + " " + hora + ":" + minuto;
            
            model.addRow(
                new Object[]{
                    consulta.getPaciente().getNome(),
                    consulta.getMedico().getNome(),
                    data,
                    consulta.getTipo()
                }
            );
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox botaoChecagemFiltro;
    private javax.swing.JButton botaoEnviarMensagem;
    private javax.swing.JButton botaoGerarRelatorio1;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoAno;
    private javax.swing.JTextField campoTextoDia;
    private javax.swing.JTextField campoTextoMes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Secretaria secretaria;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Secretaria getSecretaria() {
        return secretaria;
    }

    public void setSecretaria(Secretaria secretaria) {
        this.secretaria = secretaria;
    }
    
}
