/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Medico;
import Classes.SistemaClinicaMedica;
import javax.swing.JOptionPane;
import java.util.Calendar;

/**
 * Painel com interface para registrar o médico
 */
public class PainelRegistroMedico extends javax.swing.JPanel {
    
    /**
     * Construtor do painel
     */
    public PainelRegistroMedico() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelRegistroMedico(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoTextoCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoTextoTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTextoCRM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTextoAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoTextoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTextoDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoTextoEmail = new javax.swing.JTextField();
        campoTextoAreaMedica = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoTextoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNomeActionPerformed(evt);
            }
        });
        add(campoTextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 230, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 70, 20));

        campoTextoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFActionPerformed(evt);
            }
        });
        add(campoTextoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 230, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CPF");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 70, 20));

        campoTextoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTelefoneActionPerformed(evt);
            }
        });
        add(campoTextoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 230, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefone");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 70, 20));

        campoTextoCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCRMActionPerformed(evt);
            }
        });
        add(campoTextoCRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 230, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 70, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Senha");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 70, 20));

        campoTextoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAnoActionPerformed(evt);
            }
        });
        add(campoTextoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 50, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registrar novo médico");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 270, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ano");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 30, 20));

        campoTextoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMesActionPerformed(evt);
            }
        });
        add(campoTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 50, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mês");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 30, 20));

        campoTextoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoDiaActionPerformed(evt);
            }
        });
        add(campoTextoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 50, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 30, 20));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 230, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Data de nascimento");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 130, 20));

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        botaoRegistrar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoRegistrar.setText("Registrar");
        botaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarActionPerformed(evt);
            }
        });
        add(botaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CRM");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, 20));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Area médica");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 70, 20));

        campoTextoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEmailActionPerformed(evt);
            }
        });
        add(campoTextoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 230, -1));

        campoTextoAreaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAreaMedicaActionPerformed(evt);
            }
        });
        add(campoTextoAreaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNomeActionPerformed

    private void campoTextoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFActionPerformed

    private void campoTextoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTelefoneActionPerformed

    private void campoTextoCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCRMActionPerformed

    private void campoTextoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAnoActionPerformed

    private void campoTextoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMesActionPerformed

    private void campoTextoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoDiaActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        campoSenha.setText("");
        ((PainelClinicaMedica) getParent()).mostrarPainel("Inicio");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarActionPerformed
        if (Verificar()) {
            Medico medico = registrarMedico();
            if (medico != null) {
                mostrarPainelMedico(medico);
            }
        }
    }//GEN-LAST:event_botaoRegistrarActionPerformed

    private void campoTextoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEmailActionPerformed

    private void campoTextoAreaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAreaMedicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAreaMedicaActionPerformed

    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean Verificar() {
        boolean correto = true;
        String conteudoAviso = null;
       
       if (campoTextoNome.getText().length() == 0) {
            conteudoAviso = "Nome não foi preenchido";
            correto = false;
       }
       
       if (campoTextoCPF.getText().length() == 0) {
            conteudoAviso = "CPF não foi preenchido";
            correto = false;
       }
       
       if (campoTextoAreaMedica.getText().length() == 0) {
            conteudoAviso = "Area médica não foi preenchida";
            correto = false;
       } 
       
       if (campoTextoCRM.getText().length() == 0) {
            conteudoAviso = "CRM não foi preenchido";
            correto = false;
       } 
       
       try {
            Integer.valueOf(campoTextoAno.getText());
            Integer.valueOf(campoTextoMes.getText());
            Integer.valueOf(campoTextoDia.getText());
            
       } catch (NumberFormatException erro) {
            conteudoAviso = "A data de nascimento está incorreta";
            correto = false;
       }
       
       if (campoSenha.getPassword().length == 0) {
            conteudoAviso = "Senha não foi preenchida";
            correto = false;
       } 
       
       if (conteudoAviso != null) {
            JOptionPane.showMessageDialog(this, conteudoAviso, "Aviso", JOptionPane.WARNING_MESSAGE);
       }
       
       return correto;
    }
    
    /**
     * Cadastra o médico no banco de dados
     * @return retorna o dados registrados
     */
    private Medico registrarMedico() {
        Medico dadosRegistrados = null;
        Medico dadosMedico = new Medico();

        dadosMedico.setNome(campoTextoNome.getText());
        dadosMedico.setEmail(campoTextoEmail.getText());
        dadosMedico.setTelefone(campoTextoTelefone.getText());
        dadosMedico.setCpf(campoTextoCPF.getText());
        dadosMedico.setAreaMedica(campoTextoAreaMedica.getText());
        dadosMedico.setSenha(new String(campoSenha.getPassword()));
        dadosMedico.setCrm(campoTextoCRM.getText());
        Calendar calendar = Calendar.getInstance();
        calendar.set(
            Integer.parseInt(campoTextoAno.getText()), 
            Integer.parseInt(campoTextoMes.getText()) - 1, 
            Integer.parseInt(campoTextoDia.getText())
        );
        dadosMedico.setDataNascimento(calendar.getTime());
        
        String erro = sistema.registrarMedico(dadosMedico);
        if (erro == null) {
            dadosRegistrados = dadosMedico;
        } else {
            JOptionPane.showMessageDialog(this, erro, "Aviso", JOptionPane.WARNING_MESSAGE);
        }
       return dadosRegistrados;
    }
    
    private void mostrarPainelMedico(Medico medico) {
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        painel.getPainelMedico().setIdMedico(medico.getId());
        painel.mostrarPainel("Medico");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRegistrar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoTextoAno;
    private javax.swing.JTextField campoTextoAreaMedica;
    private javax.swing.JTextField campoTextoCPF;
    private javax.swing.JTextField campoTextoCRM;
    private javax.swing.JTextField campoTextoDia;
    private javax.swing.JTextField campoTextoEmail;
    private javax.swing.JTextField campoTextoMes;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JTextField campoTextoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }
    
    
}
