/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Paciente;
import Classes.Secretaria;
import Classes.SistemaClinicaMedica;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Painel com interface da secretária
 */
public class PainelSecretaria extends javax.swing.JPanel {

    /**
     * Construtor do painel
     */
    public PainelSecretaria() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelSecretaria(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        botaoGerarRelatorios = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        botaoRemoverPaciente = new javax.swing.JButton();
        campoTextoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoTextoCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoEditarPaciente = new javax.swing.JButton();
        tabelaPacientes = new Tabelas.TabelaPacientes(sistema);
        botaoRegistrarPaciente = new javax.swing.JButton();
        botaoGerenciarConsultas = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Sair");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        botaoGerarRelatorios.setText("Gerar relatório");
        botaoGerarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatoriosActionPerformed(evt);
            }
        });
        add(botaoGerarRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 150, -1));

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        add(botaoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, -1));

        botaoRemoverPaciente.setText("Remover paciente");
        botaoRemoverPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverPacienteActionPerformed(evt);
            }
        });
        add(botaoRemoverPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 150, -1));

        campoTextoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNomeActionPerformed(evt);
            }
        });
        add(campoTextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 40, 20));

        campoTextoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFActionPerformed(evt);
            }
        });
        add(campoTextoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 130, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CPF");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 30, 20));

        botaoEditarPaciente.setText("Editar paciente");
        botaoEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarPacienteActionPerformed(evt);
            }
        });
        add(botaoEditarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 150, -1));
        add(tabelaPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        botaoRegistrarPaciente.setText("Registrar paciente");
        botaoRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarPacienteActionPerformed(evt);
            }
        });
        add(botaoRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 150, -1));

        botaoGerenciarConsultas.setText("Gerenciar consultas");
        botaoGerenciarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerenciarConsultasActionPerformed(evt);
            }
        });
        add(botaoGerenciarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Inicio");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoGerarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatoriosActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("RelatorioConsultas");
    }//GEN-LAST:event_botaoGerarRelatoriosActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        realizarBusca();
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoRemoverPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverPacienteActionPerformed
        Paciente paciente = tabelaPacientes.obterSelecionado();
        if (paciente != null) {
            sistema.removerPaciente(paciente.getId());
            JOptionPane.showMessageDialog(
                this, 
                "Paciente removido do banco de dados com sucesso", 
                "Paciente removido", 
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um paciente antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        realizarBusca();
    }//GEN-LAST:event_botaoRemoverPacienteActionPerformed

    private void campoTextoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNomeActionPerformed

    private void campoTextoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFActionPerformed

    private void botaoEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarPacienteActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        Paciente paciente = tabelaPacientes.obterSelecionado();
        if (paciente != null) {
            painel.getPainelEdicaoPaciente().setIdPaciente(paciente.getId());
            painel.mostrarPainel("EditarPaciente");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um paciente antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoEditarPacienteActionPerformed

    private void botaoRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarPacienteActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        painel.mostrarPainel("RegistrarPaciente");
    }//GEN-LAST:event_botaoRegistrarPacienteActionPerformed

    private void botaoGerenciarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerenciarConsultasActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        Paciente paciente = tabelaPacientes.obterSelecionado();
        if (paciente != null) {
            painel.getPainelConsulta().setIdPaciente(paciente.getId());
            painel.mostrarPainel("Consulta");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um paciente antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoGerenciarConsultasActionPerformed
    
    private void realizarBusca() {
        List<Paciente> pacientes = sistema.pesquisarPacientes(campoTextoNome.getText(), campoTextoCPF.getText());
        tabelaPacientes.setPacientes(pacientes);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditarPaciente;
    private javax.swing.JButton botaoGerarRelatorios;
    private javax.swing.JButton botaoGerenciarConsultas;
    private javax.swing.JButton botaoRegistrarPaciente;
    private javax.swing.JButton botaoRemoverPaciente;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoCPF;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Tabelas.TabelaPacientes tabelaPacientes;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idSecretaria;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdSecretaria() {
        return idSecretaria;
    }

    public void setIdSecretaria(Integer secretaria) {
        this.idSecretaria = secretaria;
    }
    
}
