/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Medico;
import Classes.Secretaria;
import Classes.SistemaClinicaMedica;
import javax.swing.JOptionPane;

/**
 * Painel com a interface de acesso para usuários
 */
public class PainelAcesso extends javax.swing.JPanel {

    /**
     * Creates new form PanelTeste2
     */
    public PainelAcesso() {
        initComponents();
    }
    
    /**
     * Creates new form PanelTeste2
     * @param sistema Sistema da clínica
     */
    public PainelAcesso(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoEntrar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoTextoCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 110, -1));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Preencha os campos para entrar");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 350, 30));

        campoTextoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFActionPerformed(evt);
            }
        });
        add(campoTextoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 150, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("CPF");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 50, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SENHA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 50, 20));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        Boolean correto = true;
        String conteudoAviso = null;
        String cpf = "";
        String senha = "";
        
        if (campoTextoCPF.getText().length() == 0) {
            correto = false;
            conteudoAviso = "CPF não foi preenchido";
        } else {
            cpf = campoTextoCPF.getText();
        }
        
        if (campoSenha.getPassword().length == 0) {
            correto = false;
            conteudoAviso = "senha não foi preenchida";
        } else {
            senha = new String(campoSenha.getPassword());
        }
        
        if (correto) {
           Medico dadosMedico = sistema.obterMedico(cpf);
           if (dadosMedico != null) {
               if (senha.equals(dadosMedico.getSenha())) {
                   entrarMedico(dadosMedico);
                   limpar();
               } else {
                   conteudoAviso = "Senha incorreta";
               }
           } else {
               Secretaria dadosSecretaria = sistema.obterSecretaria(cpf);
               if (dadosSecretaria != null) {
                   if (senha.equals(dadosSecretaria.getSenha())) {
                       entrarSecretaria(dadosSecretaria);
                       limpar();
                    } else {
                       conteudoAviso = "Senha incorreta";
                    }
               } else {
                   conteudoAviso = "Esse cpf não está cadastrado";
               }
           }
       } 
       if (conteudoAviso != null) {
           JOptionPane.showMessageDialog(this, conteudoAviso, "Aviso", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void campoTextoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        limpar();
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Inicio");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void entrarMedico(Medico dadosMedicos) {
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        painel.getPainelMedico().setIdMedico(dadosMedicos.getId());
        painel.mostrarPainel("Medico");
    }
    
    private void entrarSecretaria(Secretaria dadosSecretaria) {
        PainelClinicaMedica painel = (PainelClinicaMedica) this.getParent();
        painel.getPainelSecretaria().setIdSecretaria(dadosSecretaria.getId());
        painel.mostrarPainel("Secretaria");
    }
    
    private void limpar() {
         campoTextoCPF.setText("");
         campoSenha.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoTextoCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }
    
    
}
