/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Prontuario;
import Classes.SistemaClinicaMedica;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Painel com interface para gerar relatórios de prontuários
 */
public class PainelRelatorioProntuarios extends javax.swing.JPanel {

    /**
     * Construtor do painel
     */
    public PainelRelatorioProntuarios() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelRelatorioProntuarios(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        botaoGerarRelatorio = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        campoTextoAno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoTextoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Sair");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        botaoGerarRelatorio.setText("Gerar relatório de consultas");
        botaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorioActionPerformed(evt);
            }
        });
        add(botaoGerarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 190, -1));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new java.awt.Dimension(420, 360));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 550, 470));

        campoTextoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAnoActionPerformed(evt);
            }
        });
        add(campoTextoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 50, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ano");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 30, 20));

        campoTextoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMesActionPerformed(evt);
            }
        });
        add(campoTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mês");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 30, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Medico");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioActionPerformed
        if (Verificar()) {
            gerarRelatorio();    
        }
    }//GEN-LAST:event_botaoGerarRelatorioActionPerformed

    private void campoTextoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAnoActionPerformed

    private void campoTextoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMesActionPerformed
    
    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean Verificar() {
        boolean correto;
       
       try {
            Integer.valueOf(campoTextoAno.getText());
            Integer.valueOf(campoTextoMes.getText());
            correto = true;
       } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(this, "A data está incorreta", "Aviso", JOptionPane.WARNING_MESSAGE);
            correto = false;
       }
       
       return correto;
    }
    
    private void gerarRelatorio() {
        List<Prontuario> prontuarios = sistema.pesquisarProntuarios(
            sistema.obterMedico(idMedico),
            Integer.parseInt(campoTextoAno.getText()),
            Integer.parseInt(campoTextoMes.getText()) - 1
        );
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        Calendar calendar = Calendar.getInstance();
        for (Prontuario prontuario: prontuarios) {
            calendar.setTime(prontuario.getDataCriacao());
            int ano = calendar.get(Calendar.YEAR);
            int mes = calendar.get(Calendar.MONTH) + 1;
            int dia = calendar.get(Calendar.DAY_OF_MONTH);
            int hora = calendar.get(Calendar.HOUR_OF_DAY);
            int minuto = calendar.get(Calendar.MINUTE);
            String data = ano + "/" + mes + "/" + dia + " " + hora + ":" + minuto;
            
            model.addRow(
                new Object[]{
                    prontuario.getPaciente().getNome(),
                    data
                }
            );
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoAno;
    private javax.swing.JTextField campoTextoMes;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idMedico;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdMedico() {
        return idMedico;
    }

    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    
}
