/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Consulta;
import Classes.SistemaClinicaMedica;
import javax.swing.JOptionPane;
import java.util.Calendar;

/**
 * Painel com interface para registrar paciente
 */
public class PainelEdicaoConsulta extends javax.swing.JPanel {
    
    /**
     * Construtor do painel
     */
    public PainelEdicaoConsulta() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelEdicaoConsulta(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        campoTextoTipo = new javax.swing.JTextField();
        botaoConcluir = new javax.swing.JButton();
        campoTextoAno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoTextoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTextoDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoTextoHora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoTextoMinuto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Editar consulta");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 140, 30));

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Tipo");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 40, 20));

        campoTextoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTipoActionPerformed(evt);
            }
        });
        add(campoTextoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 120, -1));

        botaoConcluir.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoConcluir.setText("Concluir");
        botaoConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConcluirActionPerformed(evt);
            }
        });
        add(botaoConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 120, -1));

        campoTextoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAnoActionPerformed(evt);
            }
        });
        add(campoTextoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ano");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, 20));

        campoTextoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMesActionPerformed(evt);
            }
        });
        add(campoTextoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 70, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mês");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 30, 20));

        campoTextoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoDiaActionPerformed(evt);
            }
        });
        add(campoTextoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 70, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 30, 20));

        campoTextoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoHoraActionPerformed(evt);
            }
        });
        add(campoTextoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 70, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Hora");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 30, 20));

        campoTextoMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMinutoActionPerformed(evt);
            }
        });
        add(campoTextoMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 70, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Minuto");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 40, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) getParent()).mostrarPainel("Consulta");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoTextoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTipoActionPerformed

    private void botaoConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConcluirActionPerformed
        if (Verificar()) {
            atualizarConsulta();
            ((PainelClinicaMedica) getParent()).mostrarPainel("Consulta");
        }
    }//GEN-LAST:event_botaoConcluirActionPerformed

    private void campoTextoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAnoActionPerformed

    private void campoTextoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMesActionPerformed

    private void campoTextoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoDiaActionPerformed

    private void campoTextoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoHoraActionPerformed

    private void campoTextoMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMinutoActionPerformed

    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean Verificar() {
        boolean correto = true;
        String conteudoAviso = null;
       
        if (campoTextoTipo.getText().length() == 0) {
             conteudoAviso = "Tipo não foi preenchido";
             correto = false;
        }

        try {
             Integer.valueOf(campoTextoAno.getText());
             Integer.valueOf(campoTextoMes.getText());
             Integer.valueOf(campoTextoDia.getText());
             Integer.valueOf(campoTextoDia.getText());
             Integer.valueOf(campoTextoDia.getText());

        } catch (NumberFormatException erro) {
             conteudoAviso = "A data de nascimento está incorreta";
             correto = false;
        }

        if (conteudoAviso != null) {
             JOptionPane.showMessageDialog(this, conteudoAviso, "Aviso", JOptionPane.WARNING_MESSAGE);
        }

        return correto;
    }
    
    /**
     * Cadastra a consulta no banco de dados
     */
    private void atualizarConsulta() {
        Consulta consulta = new Consulta();
        
        consulta.setTipo(campoTextoTipo.getText());
        Calendar calendar = Calendar.getInstance();
        calendar.set(
            Integer.parseInt(campoTextoAno.getText()), 
            Integer.parseInt(campoTextoMes.getText()) - 1, 
            Integer.parseInt(campoTextoDia.getText())
        );
        calendar.set(Calendar.HOUR_OF_DAY, Integer.parseInt(campoTextoHora.getText()));
        calendar.set(Calendar.MINUTE, Integer.parseInt(campoTextoMinuto.getText()));
        
        
        sistema.atualizarConsulta(idConsulta, calendar.getTime(), campoTextoTipo.getText());
        JOptionPane.showMessageDialog(this, 
            "Consulta atualizada com sucesso", 
            "Consulta atualizada", 
            JOptionPane.INFORMATION_MESSAGE
        );
        
    }
    
    /**
     * Atualiza os campos de texto da interface
     */
    public void atualizarCampos() {
        Consulta consulta = sistema.obterConsulta(idConsulta);
        campoTextoTipo.setText(consulta.getTipo());
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(consulta.getDataMarcada());
        campoTextoAno.setText(Integer.toString(calendar.get(Calendar.YEAR)));
        campoTextoMes.setText(Integer.toString(calendar.get(Calendar.MONTH) + 1));
        campoTextoDia.setText(Integer.toString(calendar.get(Calendar.DAY_OF_MONTH)));
        campoTextoHora.setText(Integer.toString(calendar.get(Calendar.HOUR_OF_DAY)));
        campoTextoMinuto.setText(Integer.toString(calendar.get(Calendar.MINUTE)));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoAno;
    private javax.swing.JTextField campoTextoDia;
    private javax.swing.JTextField campoTextoHora;
    private javax.swing.JTextField campoTextoMes;
    private javax.swing.JTextField campoTextoMinuto;
    private javax.swing.JTextField campoTextoTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idConsulta;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdConsulta() {
        return idConsulta;
    }

    public void setIdConsulta(Integer idConsulta) {
        this.idConsulta = idConsulta;
        atualizarCampos();
    }
    
    
}
