/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

/**
 * Painel com a interface inicial
 */
public class PainelInicial extends javax.swing.JPanel {

    /**
     * Construtor do painel
     */
    public PainelInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoEntrar = new javax.swing.JButton();
        botaoRegistrarMedico = new javax.swing.JButton();
        botaoRegistrarSecretaria = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 190, -1));

        botaoRegistrarMedico.setText("Registrar médico");
        botaoRegistrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarMedicoActionPerformed(evt);
            }
        });
        add(botaoRegistrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 190, -1));

        botaoRegistrarSecretaria.setText("Registrar secretária");
        botaoRegistrarSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarSecretariaActionPerformed(evt);
            }
        });
        add(botaoRegistrarSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Acessar");
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoRegistrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarMedicoActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("RegistrarMedico");
    }//GEN-LAST:event_botaoRegistrarMedicoActionPerformed

    private void botaoRegistrarSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarSecretariaActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("RegistrarSecretaria");
    }//GEN-LAST:event_botaoRegistrarSecretariaActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        System.out.println("Ganhou");
    }//GEN-LAST:event_formFocusGained
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoRegistrarMedico;
    private javax.swing.JButton botaoRegistrarSecretaria;
    // End of variables declaration//GEN-END:variables

}
