/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Prontuario;
import Classes.SistemaClinicaMedica;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 * Painel com interface para gerenciamento de prontuarios
 */
public class PainelProntuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelTeste2
     */
    public PainelProntuario() {
        initComponents();
    }
    
    /**
     * Creates new form PanelTeste2
     * @param sistema Sistema da clínica
     */
    public PainelProntuario(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        botaoGerarDeclaracao = new javax.swing.JButton();
        campoTextoPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botaoEditarProntuario = new javax.swing.JButton();
        botaoRegistrarConsulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tabelaProntuarios = new Tabelas.TabelaProntuarios();
        campoTextoMedico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botaoRemoverProntuario = new javax.swing.JButton();
        botaoGerarAtestado = new javax.swing.JButton();
        botaoGerarReceita = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Sair");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        add(botaoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 140, -1));

        botaoGerarDeclaracao.setText("Gerar declaração de acompanhamento");
        botaoGerarDeclaracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarDeclaracaoActionPerformed(evt);
            }
        });
        add(botaoGerarDeclaracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 170, -1));

        campoTextoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoPacienteActionPerformed(evt);
            }
        });
        add(campoTextoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Paciente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 20));

        botaoEditarProntuario.setText("Editar prontuário");
        botaoEditarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarProntuarioActionPerformed(evt);
            }
        });
        add(botaoEditarProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 170, -1));

        botaoRegistrarConsulta.setText("Registrar prontuário");
        botaoRegistrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarConsultaActionPerformed(evt);
            }
        });
        add(botaoRegistrarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Prontuários");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));
        add(tabelaProntuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        campoTextoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMedicoActionPerformed(evt);
            }
        });
        add(campoTextoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 130, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Medico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, 20));

        botaoRemoverProntuario.setText("Remover prontuário");
        botaoRemoverProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverProntuarioActionPerformed(evt);
            }
        });
        add(botaoRemoverProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 170, -1));

        botaoGerarAtestado.setText("Gerar atestado");
        botaoGerarAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarAtestadoActionPerformed(evt);
            }
        });
        add(botaoGerarAtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 170, -1));

        botaoGerarReceita.setText("Gerar receita");
        botaoGerarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarReceitaActionPerformed(evt);
            }
        });
        add(botaoGerarReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) this.getParent()).mostrarPainel("Medico");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        realizarBusca();
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoGerarDeclaracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarDeclaracaoActionPerformed
        Prontuario prontuario = tabelaProntuarios.obterSelecionado();
        if (prontuario != null) {
            String nomeAcompanhante = JOptionPane.showInputDialog(
                this,
                "Informe o nome do acompanhante:"
            );
            String declaracao =
                "Declaro para os devidos fins que " + nomeAcompanhante +
                " acompanhou o(a) paciente " +
                prontuario.getPaciente().getNome() +
                " em consulta médica.\n" +
                "Médico: " + prontuario.getMedico().getNome() + "\n" +
                "Data: " + prontuario.getDataCriacao() + "\n";

            JOptionPane.showMessageDialog(
                this,
                declaracao,
                "Declaração de acompanhamento",
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma prontuario antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoGerarDeclaracaoActionPerformed

    private void campoTextoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoPacienteActionPerformed

    private void botaoEditarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarProntuarioActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        Prontuario prontuario = tabelaProntuarios.obterSelecionado();
        if (prontuario != null) {
            if (Objects.equals(prontuario.getMedico().getId(), idMedico)) {
                painel.getPainelEdicaoProntuario().setIdProntuario(prontuario.getId());
                painel.mostrarPainel("EditarProntuario");
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "Só é permitido editar prontuários que você cadastrou", 
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma prontuario antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoEditarProntuarioActionPerformed

    private void botaoRegistrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarConsultaActionPerformed
        PainelClinicaMedica painel = (PainelClinicaMedica) getParent();
        painel.getPainelRegistroProntuario().setIdPaciente(idPaciente);
        painel.getPainelRegistroProntuario().setIdMedico(idMedico);
        painel.mostrarPainel("RegistrarProntuario");
    }//GEN-LAST:event_botaoRegistrarConsultaActionPerformed

    private void campoTextoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMedicoActionPerformed

    private void botaoRemoverProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverProntuarioActionPerformed
        Prontuario prontuario = tabelaProntuarios.obterSelecionado();
        if (prontuario != null) {
            if (Objects.equals(prontuario.getMedico().getId(), idMedico)) {
                sistema.removerProntuario(prontuario.getId());
                realizarBusca();
                JOptionPane.showMessageDialog(
                    this, 
                    "Prontuário removido do banco de dados com sucesso", 
                    "Prontuário removido", 
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "Só é permitido editar prontuários que você cadastrou", 
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma prontuario antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_botaoRemoverProntuarioActionPerformed

    private void botaoGerarAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarAtestadoActionPerformed
        Prontuario prontuario = tabelaProntuarios.obterSelecionado();
        if (prontuario != null) {
            String atestado = "Atesto para os devidos fins que o(a) paciente " +
            prontuario.getPaciente().getNome() +
            " esteve em consulta médica.\n" +
            "Médico: " + prontuario.getMedico().getNome() + "\n" +
            "Data: " + prontuario.getDataCriacao();
        JOptionPane.showMessageDialog(
            this,
            atestado,
            "Atestado médico",
            JOptionPane.INFORMATION_MESSAGE
        );
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma prontuario antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoGerarAtestadoActionPerformed

    private void botaoGerarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarReceitaActionPerformed
        Prontuario prontuario = tabelaProntuarios.obterSelecionado();
        if (prontuario != null) {
            String receita = "Paciente: " + prontuario.getPaciente().getNome() + "\n" +
                "Médico: " + prontuario.getMedico().getNome() + "\n" +
                "Data: " + prontuario.getDataCriacao() + "\n" + 
                "Prescrição:\n" + prontuario.getPrescricao();
            JOptionPane.showMessageDialog(
                this, 
                receita,
                "Receita gerada", 
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma prontuario antes", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoGerarReceitaActionPerformed
    
    private void realizarBusca() {
        List<Prontuario> prontuarios = sistema.pesquisarProntuario(
            campoTextoPaciente.getText(),
            campoTextoMedico.getText()
        );
        tabelaProntuarios.setProntuarios(prontuarios);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditarProntuario;
    private javax.swing.JButton botaoGerarAtestado;
    private javax.swing.JButton botaoGerarDeclaracao;
    private javax.swing.JButton botaoGerarReceita;
    private javax.swing.JButton botaoRegistrarConsulta;
    private javax.swing.JButton botaoRemoverProntuario;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoTextoMedico;
    private javax.swing.JTextField campoTextoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private Tabelas.TabelaProntuarios tabelaProntuarios;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idMedico;
    private Integer idPaciente;

    public Integer getIdMedico() {
        return idMedico;
    }

    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    
    public Integer getIdPaciente() {
        return idPaciente;
    }

    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }
    
}
