/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paineis;

import Classes.Prontuario;
import Classes.SistemaClinicaMedica;
import javax.swing.JOptionPane;

/**
 * Painel com interface para registrar paciente
 */
public class PainelEdicaoProntuario extends javax.swing.JPanel {
    
    /**
     * Construtor do painel
     */
    public PainelEdicaoProntuario() {
        initComponents();
    }
    
    /**
     * Construtor do painel
     * @param sistema Sistema da clínica
     */
    public PainelEdicaoProntuario(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        botaoConcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoSintomas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTextoDiagnosticos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTextoPrescricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Editar prontuário");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 140, 30));

        botaoVoltar.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        botaoConcluir.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        botaoConcluir.setText("Concluir");
        botaoConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConcluirActionPerformed(evt);
            }
        });
        add(botaoConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 120, -1));

        areaTextoSintomas.setColumns(20);
        areaTextoSintomas.setRows(5);
        jScrollPane1.setViewportView(areaTextoSintomas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 480, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Sintomas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, -1));

        areaTextoDiagnosticos.setColumns(20);
        areaTextoDiagnosticos.setRows(5);
        jScrollPane2.setViewportView(areaTextoDiagnosticos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 480, 100));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Diagnóstico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 120, -1));

        areaTextoPrescricao.setColumns(20);
        areaTextoPrescricao.setRows(5);
        jScrollPane3.setViewportView(areaTextoPrescricao);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 480, 100));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Prescrição");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        ((PainelClinicaMedica) getParent()).mostrarPainel("Prontuario");
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConcluirActionPerformed
        if (Verificar()) {
            atualizarProntuario();
            ((PainelClinicaMedica) getParent()).mostrarPainel("Prontuario");
        }
    }//GEN-LAST:event_botaoConcluirActionPerformed

    /**
     * Verifica a integridade dos dados escritos
     * @return Se os dados estão corretos
     */
    private boolean Verificar() {
        boolean correto = true;
        String conteudoAviso = null;
       
       if (areaTextoSintomas.getText().length() == 0) {
            conteudoAviso = "Nenhum sintoma escrito";
            correto = false;
       }
       
       if (areaTextoDiagnosticos.getText().length() == 0) {
            conteudoAviso = "Nenhum diagnóstico escrito";
            correto = false;
       }
       if (areaTextoPrescricao.getText().length() == 0) {
            conteudoAviso = "Nenhuma prescrição escrita";
            correto = false;
       }
       
       if (conteudoAviso != null) {
            JOptionPane.showMessageDialog(this, conteudoAviso, "Aviso", JOptionPane.WARNING_MESSAGE);
       }
       
       return correto;
    }
    
    /**
     * Cadastra a prontuario no banco de dados
     */
    private void atualizarProntuario() {
        sistema.atualizarProntuario(
            idProntuario,
            areaTextoSintomas.getText(),
            areaTextoDiagnosticos.getText(),
            areaTextoPrescricao.getText()
        );
        
    }
    
    /**
     * Atualiza os campos de texto da interface
     */
    public void atualizarCampos() {
        Prontuario prontuario = sistema.obterProntuario(idProntuario);
        
        areaTextoSintomas.setText(prontuario.getSintomas());
        areaTextoDiagnosticos.setText(prontuario.getDiagnosticos());
        areaTextoPrescricao.setText(prontuario.getPrescricao());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoDiagnosticos;
    private javax.swing.JTextArea areaTextoPrescricao;
    private javax.swing.JTextArea areaTextoSintomas;
    private javax.swing.JButton botaoConcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private SistemaClinicaMedica sistema;
    private Integer idProntuario;

    public SistemaClinicaMedica getSistema() {
        return sistema;
    }

    public void setSistema(SistemaClinicaMedica sistema) {
        this.sistema = sistema;
    }

    public Integer getIdProntuario() {
        return idProntuario;
    }

    public void setIdProntuario(Integer idProntuario) {
        this.idProntuario = idProntuario;
        atualizarCampos();
    }
    
}
